name: Test

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --no-ansi --no-interaction --no-progress --no-suggest --prefer-dist

      - name: Run Tests
        run: vendor/bin/phpunit
